// Mocks generated by Mockito 5.4.6 from annotations
// in shop_me/test/src/repositories/category_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:shop_me/data/models/category_response.dart' as _i5;
import 'package:shop_me/data/repositories/category_repository.dart' as _i2;
import 'package:shop_me/data/services/network/result_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i2.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ResultState<List<_i5.Category>>> fetchCategories() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCategories, []),
            returnValue: _i3.Future<_i4.ResultState<List<_i5.Category>>>.value(
              _i6.dummyValue<_i4.ResultState<List<_i5.Category>>>(
                this,
                Invocation.method(#fetchCategories, []),
              ),
            ),
          )
          as _i3.Future<_i4.ResultState<List<_i5.Category>>>);
}
